services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: mi_usuario
      POSTGRES_PASSWORD: mi_password_seguro
      POSTGRES_DB: mi_base_de_datos
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata: