info:
  name: put
  type: http
  seq: 5

http:
  method: PUT
  url: "{{baseDEV}}/tasks/:id"
  params:
    - name: id
      value: cmp5mb6nz0007cayi9btp3ejk
      type: path
  body:
    type: json
    data: |-
      {
        "column_id": "column-1",
        "title": "Tarea actualizada",
        "description": "Nueva descripción",
        "order": 2,
        "due_date": "2025-12-31T00:00:00.000Z"
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
